evropat
kachvame/evropat pull request #1
Opened 2022-01-12 18:28 UTC by zahari00

2022-01-12 18:29 UTC, fr3fou requested changes
miguel?

2022-01-12 18:33 UTC, invakid404 approved these changes
miguel indeed

2022-01-12 18:34 UTC, invakid404 commented
@fr3fou kolega, davai da go kachvame, che nqma vreme

2022-01-12 18:34 UTC, fr3fou approved these changes

2022-01-12 18:35 UTC, todortotev requested changes
LBTM

2022-01-12 18:36 UTC, invakid404 commented
@todortotev nqma vreme :)

2022-01-12 18:36 UTC, dzhembekir9 requested changes
noob

2022-01-12 18:40 UTC, Minchev98 commented
sled 15 min malak fix

2022-01-12 18:53 UTC, invakid404 commented
kachvame go

2022-01-12 18:53 UTC, merged

2022-01-13 07:38 UTC, ablax commented
Reverting - malkata vidra lipsva